# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reality is merely an illusion, albeit a very persistent one.
email: sahmed9@buffalo.edu

author:
        name: Saleem Ahmed 
        email: sahmed9@buffalo.edu
        picture: /oldsite/img/index.jpeg
        social: 
                twitter: crazysal
                github: crazysal

description: >- 
        Saleem Ahmed is an accomplished Computer Vision research scholar. He dabbles in all kinds things computer science. 
        With an ongoing summer research internship @ Ericsson Research -Santa clara, focusing on recognition and segmentation on multiple video sources,
        he also brings to the table 3+ years as a professional software engineer.
        He is currently on his way of navigating through grad school @UB.
        
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crazysal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: crazysal
github_username:  crazysal

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
#
#url: http://salahm.com/
#baseurl: ''
